extends Node
## Audio manager (autoload "Sfx").
##   Sfx.play(name, pos := Vector3.INF, vol_db := 0.0, pitch := 1.0)   one-shot SFX (distance-attenuated if pos)
##   Sfx.music(name)                                                    crossfade to a looping track ("" = silence)
##   Sfx.loop(name, node, vol_db)                                       looping emitter following a node
## Files live in res://assets/audio/{sfx,music,amb}/<name>.ogg; missing files are ignored silently. The DOCE sound
## set and where each sound belongs: docs/AUDIO.md (generated by doce/tools/audio).
##
## By itself, every frame:
##  - the ambience beds follow the hero: `sea` near the coast, `wind` up high, `day` (birds, cicadas) outdoors,
##    `cave` inside the Lion's cave (the others drop away). World hooks used when present: `coast_distance(x, z)`,
##    `cave_amount(pos) -> 0..1`; otherwise is_water() probes and the distance to World.cave().arena_center.
##  - the music follows the game while auto_music is on: `explore` on the island, `tension` near the cave mouths,
##    `boss_lion` from Game.boss_started to boss_ended, silence under the victory stinger, ducked while the hero
##    is down. Callers may still pick a track with Sfx.music(); the director only moves between its own tracks.
##  - PHAROS names still used by older calls are mapped to their DOCE sounds (RENAMES).
## Debug: `audiodebug=1` prints the mix (music, beds, surroundings) every 2 s.

const POOL := 22
## Old name -> DOCE name ("dir/name" -> name). Callers should switch to the new names; this keeps old calls working.
const RENAMES := {
	"music/title": "explore", "music/day": "explore",
	"sfx/blessing": "altar", "sfx/orb_hit": "chain_stick", "sfx/structure_hit": "chain_stick",
}
const BEDS := ["sea", "wind", "day", "cave"]
## Music director: `tension` within this distance (m) of a cave mouth (leaves at TENSION_OUT, hysteresis).
const TENSION_IN := 55.0
const TENSION_OUT := 70.0
## Silence after a won boss fight (the stinger plays), then `explore` again.
const VICTORY_HOLD := 9.0

## Off: the music only changes when someone calls Sfx.music().
var auto_music := true
## 0..1 forced cave amount (a scripted moment), or -1 to measure it.
var cave_override := -1.0

var _players: Array[AudioStreamPlayer] = []
var _next := 0
var _cache := {}
var _recent := {}
var _music_a: AudioStreamPlayer
var _music_b: AudioStreamPlayer
var _music_cur: AudioStreamPlayer = null
var _music_name := ""
var _stinger: AudioStreamPlayer
var _amb := {}
var _night := 0.0
var _fade_jobs: Array = []
## Web: sounds still to be decoded ahead of their first play() (see _web_preload).
var _sample_queue: Array[String] = []
var _sample_wait := 0.0
# surroundings of the hero (0..1), measured a few times a second
var _env_t := 0.0
var _coast := 0.6
var _height := 0.0
var _cave := 0.0
var _cave_dist := INF
# music director
var _boss := false
var _hold_until := 0.0
var _ducked := false
var _debug_t := 0


func _ready() -> void:
	process_mode = Node.PROCESS_MODE_ALWAYS
	_make_bus("Music", Settings.get_v("music"))
	_make_bus("SFX", Settings.get_v("sfx"))
	_make_bus("Amb", Settings.get_v("sfx"))
	for i in POOL:
		var p := AudioStreamPlayer.new()
		p.bus = "SFX"
		add_child(p)
		_players.append(p)
	_music_a = _new_player("Music")
	_music_b = _new_player("Music")
	_stinger = _new_player("Music")
	for n in BEDS:
		var p := _new_player("Amb")
		p.volume_db = -80.0
		_amb[n] = p
	# A little headroom: a busy fight sums above full scale.
	AudioServer.set_bus_volume_db(0, -2.5)
	Game.boss_started.connect(_on_boss_started)
	Game.boss_ended.connect(_on_boss_ended)
	Game.phase_changed.connect(_on_phase)
	if OS.has_feature("web"):
		_web_preload()


## On the web every sound is a Web Audio sample, decoded whole on its first play(): a 60 s track blocks the main
## thread for 0.3-1.2 s. Decode what the title and the island need now (under the loading screen), the short
## effects a few at a time while the title shows, the rest after them, and the boss music when a boss fight starts
## (if it is not decoded by then).
func _web_preload() -> void:
	for key in ["music/explore", "amb/sea", "amb/wind", "amb/day"]:
		_register_sample(key)
	for f in ResourceLoader.list_directory("res://assets/audio/sfx"):
		if f.ends_with(".ogg"):
			_sample_queue.append("sfx/" + f.get_basename())
	_sample_queue.append_array(["amb/cave", "amb/boulder_drag", "music/stinger_death", "music/stinger_victory",
		"music/tension", "music/boss_lion"])


func _register_sample(key: String) -> void:
	var parts := key.split("/")
	var s := _stream(parts[0], parts[1], parts[0] != "sfx" and not parts[1].begins_with("stinger_"))
	if s and not AudioServer.is_stream_registered_as_sample(s):
		AudioServer.register_stream_as_sample(s)


func _new_player(bus: String) -> AudioStreamPlayer:
	var p := AudioStreamPlayer.new()
	p.bus = bus
	add_child(p)
	return p


func _make_bus(bus_name: String, vol: float) -> void:
	if AudioServer.get_bus_index(bus_name) != -1:
		return
	# Not add_bus(): with the web's Sample playback Godot 4.7 then loops the sample buses with Master and nothing is
	# heard. Growing bus_count appends the bus the same way on every platform.
	var i := AudioServer.bus_count
	AudioServer.bus_count = i + 1
	AudioServer.set_bus_name(i, bus_name)
	AudioServer.set_bus_send(i, "Master")
	AudioServer.set_bus_volume_db(i, linear_to_db(maxf(vol, 0.0001)))


func set_volume(bus_name: String, v: float) -> void:
	var i := AudioServer.get_bus_index(bus_name)
	if i >= 0:
		AudioServer.set_bus_volume_db(i, linear_to_db(maxf(v, 0.0001)))
		AudioServer.set_bus_mute(i, v <= 0.001)


## The DOCE name for `sound` in `dir` (RENAMES maps the PHAROS names still used by older calls).
func _resolve(dir: String, sound: String) -> String:
	return String(RENAMES.get(dir + "/" + sound, sound))


func _stream(dir: String, sound: String, looped: bool = false) -> AudioStream:
	var key := dir + "/" + sound
	if _cache.has(key):
		return _cache[key]
	var path := "res://assets/audio/%s/%s.ogg" % [dir, sound]
	var s: AudioStream = null
	if ResourceLoader.exists(path):
		s = load(path)
		if looped and s is AudioStreamOggVorbis:
			(s as AudioStreamOggVorbis).loop = true
	_cache[key] = s
	return s


func _hero() -> Node3D:
	var h = Game.hero
	if h != null and is_instance_valid(h) and h is Node3D and (h as Node3D).is_inside_tree():
		return h
	return null


## Where the ears are: the hero while there is one, else the active camera.
func _listener() -> Vector3:
	var h := _hero()
	if h:
		return h.global_position
	var vp := get_viewport()
	var cam := vp.get_camera_3d() if vp else null
	return cam.global_position if cam else Vector3.ZERO


func play(sound: String, pos: Vector3 = Vector3.INF, vol_db: float = 0.0, pitch: float = 1.0) -> void:
	if sound.begins_with("stinger_"):
		var st := _stream("music", sound)
		if st:
			_stinger.stream = st
			_stinger.volume_db = vol_db
			_stinger.play()
		return
	sound = _resolve("sfx", sound)
	var s := _stream("sfx", sound)
	if s == null:
		return
	var now := Time.get_ticks_msec()
	if _recent.get(sound, -1000) > now - 35:
		return
	_recent[sound] = now
	if pos.is_finite():
		var ear := _listener()
		var d := Vector2(pos.x - ear.x, pos.z - ear.z).length()
		vol_db -= clampf((d - 10.0) * 0.55, 0.0, 40.0)
		if vol_db < -38.0:
			return
	# Prefer a voice that has finished; steal the next one in turn only when all of them are busy.
	var idx := _next
	for k in POOL:
		var i := (_next + k) % POOL
		if not _players[i].playing:
			idx = i
			break
	var p := _players[idx]
	_next = (idx + 1) % POOL
	p.stream = s
	p.volume_db = vol_db
	p.pitch_scale = clampf(pitch, 0.25, 4.0)
	p.play()


func music(track: String, fade: float = 1.6) -> void:
	if track != "":
		track = _resolve("music", track)
	if track == _music_name:
		return
	_music_name = track
	var old := _music_cur
	if old:
		_fade(old, -60.0, fade, true)
	if track == "":
		_music_cur = null
		return
	var s := _stream("music", track, true)
	if s == null:
		_music_cur = null
		return
	var p := _music_a if old != _music_a else _music_b
	p.stream = s
	p.volume_db = -40.0
	p.play()
	_fade(p, _music_level(), fade, false)
	_music_cur = p


## The name of the track playing (or fading in), "" for silence.
func current_music() -> String:
	return _music_name


func _music_level() -> float:
	return -16.0 if _ducked else -4.0


func _fade(p: AudioStreamPlayer, to_db: float, dur: float, stop_after: bool) -> void:
	for j in _fade_jobs:
		if j[0] == p:
			_fade_jobs.erase(j)
			break
	_fade_jobs.append([p, p.volume_db, to_db, 0.0, maxf(dur, 0.01), stop_after])


# --- the music follows the game ----------------------------------------------------------------------------

func _on_boss_started(_boss_name: String, _b: Node) -> void:
	_boss = true
	if OS.has_feature("web"):
		_register_sample("music/boss_lion")
	if auto_music:
		music("boss_lion", 1.0)


func _on_boss_ended(victory: bool) -> void:
	_boss = false
	if not auto_music:
		return
	if victory:
		# main.victory() plays stinger_victory: let it ring alone, then the island again
		music("", 1.2)
		_hold_until = _now() + VICTORY_HOLD
	else:
		music("tension" if _cave_dist < TENSION_OUT else "explore", 3.0)


func _on_phase(_p: int) -> void:
	if Game.phase == Game.Phase.VICTORY and _boss:
		_on_boss_ended(true) # main.victory() without a boss_ended before it
	var down: bool = Game.phase == Game.Phase.DEAD
	if down == _ducked:
		return
	_ducked = down
	if _music_cur:
		_fade(_music_cur, _music_level(), 0.6 if down else 2.0, false)


func _now() -> float:
	return Time.get_ticks_msec() / 1000.0


## explore <-> tension by the cave mouths, and explore again after the victory silence. Only touches the
## director's own tracks, so a track picked by a caller (or the boss music) stays.
func _direct_music() -> void:
	if not auto_music or _boss or _now() < _hold_until:
		return
	if not (Game.phase == Game.Phase.PLAY or Game.phase == Game.Phase.VICTORY):
		return
	if not (_music_name in ["explore", "tension", ""]):
		return
	var want := "explore"
	if _cave_dist < TENSION_IN or (_music_name == "tension" and _cave_dist < TENSION_OUT):
		want = "tension"
	if want != _music_name:
		music(want, 3.0 if _music_name != "" else 2.0)


# --- ambience ----------------------------------------------------------------------------------------------

## Measures the hero's surroundings (a few times a second): coast 0..1 (1 at the shore), height 0..1 (1 on the
## ridge), cave 0..1 (1 inside the Lion's cave) and the distance to the nearest cave mouth.
func _measure_env() -> void:
	var h := _hero()
	var w = Game.world
	if h == null or w == null or not is_instance_valid(w):
		return
	var p := h.global_position
	var sea := float(w.get("sea_level")) if "sea_level" in w else 0.0
	# coast
	if w.has_method("coast_distance"):
		_coast = 1.0 - clampf(float(w.call("coast_distance", p.x, p.z)) / 70.0, 0.0, 1.0)
	elif w.has_method("is_water"):
		var near := 90.0
		for r: float in [12.0, 30.0, 55.0, 85.0]:
			for k in 8:
				var a := TAU * float(k) / 8.0
				if bool(w.call("is_water", p.x + cos(a) * r, p.z + sin(a) * r)):
					near = minf(near, r)
			if near < 90.0:
				break
		_coast = 1.0 - clampf((near - 8.0) / 80.0, 0.0, 1.0)
	# height above the sea
	_height = clampf((p.y - sea - 10.0) / 40.0, 0.0, 1.0)
	# the cave: the world's own answer when it has one, else the distance to the arena
	_cave_dist = INF
	var cave_k := 0.0
	var c: Dictionary = w.call("cave") if w.has_method("cave") else {}
	for key in ["entrance_a", "entrance_b"]:
		if c.has(key) and c[key] is Vector3:
			_cave_dist = minf(_cave_dist, p.distance_to(c[key]))
	if w.has_method("cave_amount"):
		cave_k = clampf(float(w.call("cave_amount", p)), 0.0, 1.0)
	elif c.has("arena_center") and c["arena_center"] is Vector3:
		var d := p.distance_to(c["arena_center"])
		cave_k = 1.0 - clampf((d - 16.0) / 12.0, 0.0, 1.0)
		_cave_dist = minf(_cave_dist, d)
	_cave = cave_override if cave_override >= 0.0 else cave_k


## Ambience mix: the sea by the coast, wind up high, birds and cicadas outdoors by day (TimeOfDay.night_amount()
## lowers them), the cave's drips and echo inside it (the outdoor beds drop away there). Called every frame.
func set_ambience(night: float, active: bool = true, delta: float = 0.016) -> void:
	_night = night
	var cave := _cave
	var targets := {
		"sea": lerpf(-26.0, -14.0, _coast),
		"wind": lerpf(-30.0, -16.0, _height),
		"day": lerpf(-18.0, -50.0, night),
		"cave": lerpf(-80.0, -12.0, cave),
	}
	var k := 1.0 - exp(-delta * 2.5)
	for n in _amb:
		var p: AudioStreamPlayer = _amb[n]
		if p.stream == null:
			p.stream = _stream("amb", n, true)
			if p.stream:
				p.play()
		var t: float = targets[n]
		if n != "cave":
			t = lerpf(t, -40.0, cave)
		p.volume_db = lerpf(p.volume_db, t if active else -80.0, k)


func loop(sound: String, node: Node3D, vol_db: float = 0.0) -> Node:
	var s := _stream("amb", sound, true)
	if s == null:
		return null
	var p := AudioStreamPlayer3D.new()
	p.stream = s
	p.volume_db = vol_db
	p.bus = "Amb"
	p.unit_size = 6.0
	node.add_child(p)
	p.play()
	return p


func _process(delta: float) -> void:
	# real seconds: fades and the ambience ignore hit-stop and slow motion
	# real seconds (hit-stop and slow motion undone): Game.real_delta(), see docs/COMBAT.md 3.5
	var g: Node = get_node_or_null(^"/root/Game")
	var rd := minf(float(g.call("real_delta", delta)) if g != null and g.has_method("real_delta") else delta / maxf(Engine.time_scale, 0.001), 0.1)
	if not _sample_queue.is_empty():
		_sample_wait -= rd
		if _sample_wait <= 0.0:
			_register_sample(_sample_queue.pop_front())
			_sample_wait = 0.05
	for i in range(_fade_jobs.size() - 1, -1, -1):
		var j: Array = _fade_jobs[i]
		j[3] += rd
		var k: float = clampf(j[3] / j[4], 0.0, 1.0)
		var p: AudioStreamPlayer = j[0]
		p.volume_db = lerpf(j[1], j[2], k)
		if k >= 1.0:
			if j[5]:
				p.stop()
			_fade_jobs.remove_at(i)
	_env_t -= rd
	if _env_t <= 0.0:
		_env_t = 0.25
		_measure_env()
		_direct_music()
		if Game.arg_on("audiodebug"):
			_debug_t += 1
			if _debug_t % 8 == 0:
				print("SFX t=%.0fs phase=%s music=%s coast=%.2f height=%.2f cave=%.2f mouth=%.0fm | sea=%.0f wind=%.0f day=%.0f cave=%.0f dB" % [
					_now(), Game.phase_name(), _music_name if _music_name != "" else "-", _coast, _height, _cave,
					minf(_cave_dist, 9999.0), _amb["sea"].volume_db, _amb["wind"].volume_db, _amb["day"].volume_db,
					_amb["cave"].volume_db])
	var night := 0.0
	if Game.tod and is_instance_valid(Game.tod) and Game.tod.has_method("night_amount"):
		night = float(Game.tod.night_amount())
	set_ambience(night, Game.phase != Game.Phase.BOOT, rd)
