# Station architecture, runtime half (port of the runtime parts of src/world/architecture.js).
#
# Every static mesh of architecture.js (floors with edge AO, walls with per-area finishes, the brick shell, ceilings,
# thresholds, MC floor plates, stage / stair / riser / bleachers / rails, the Yard fence, roofs, the booth glass and
# the ceiling fixtures' frames, cans and pipe grids) is generated by blender/world/architecture.py into
# res://assets/world/architecture.glb. What stays at runtime are the fixture records: the lens mesh of each indoor
# area's ceiling fixtures (node fixtures_<areaId>, "da".fixture) whose material switches at Sign-On, and its light
# anchors registered with game.lights.
#
# buildFixtures(game, areaRoots) -> [{ area, mesh, pre:{mat}, post:{mat}, anchors:[{ id, pre:{color,intensity},
#   post:{color,intensity} }], center:Vector3, dist }]
#   pre/post = the fixture lens material before / after Sign-On; anchors = the area's ceiling light anchors
#   (lvl_<areaId>_<n>, added to game.lights with their pre colour/intensity); dist = metres from the Sign-On lever to
#   the nearest point of the area (the colour wave reaches it at dist / 15 s).
extends RefCounted

const Surf = preload("res://scripts/world/surfaces.gd")

static func indoor(id) -> bool:
	return id != null and Layout.AREA.has(id) and not Layout.AREA[id].get("sky", false)

static func buildFixtures(game, areaRoots: Dictionary) -> Array:
	var out := []
	for a in Layout.AREAS:
		if not indoor(a.id):
			continue
		var root: Node = areaRoots.get(a.id)
		var mesh := root.find_child("fixtures_" + a.id, true, false) as MeshInstance3D if root != null else null
		if mesh == null:
			push_warning("[architecture] fixtures_%s missing (run blender/build_all.py --only world)" % a.id)
			continue
		var f = Surf.nodeDa(mesh)
		f = f.get("fixture") if f != null else null
		if not (f is Dictionary):
			continue
		DAU.ud(mesh).noMerge = true
		var base := Surf.importedMat(mesh)
		var preMat := Surf.matFromSpec(game, f.pre, base)
		var postMat := Surf.matFromSpec(game, f.post, base)
		mesh.material_override = preMat
		var anchors := []
		for an in f.anchors:
			if game != null and game.lights != null and game.lights.has_method("addAnchor"):
				game.lights.addAnchor({"id": an.id, "pos": DAU.v3(an.pos), "color": an.pre.color, "intensity": an.pre.intensity,
					"distance": an.distance, "area": a.id})
			anchors.append({"id": an.id, "pre": an.pre, "post": an.post})
		out.append({
			"area": a.id, "mesh": mesh, "pre": {"mat": preMat}, "post": {"mat": postMat}, "anchors": anchors,
			"center": DAU.v3(f.center), "dist": float(f.dist),
		})
	return out
