# Everything outside the walls, runtime half (port of the runtime parts of src/world/exterior.js).
#
# The geometry (lawn, the station parking lot with stall lines, the front sidewalk and curb, the night street with
# its dashed centre line and sodium lamps + additive light pools, the neon-signed 70s storefronts, the ring of
# skyline blocks with lit window grids and their red beacons, the transmitter tower placeholder, the sky dome, the
# 900 stars and the moon) is generated by blender/world/exterior.py into res://assets/world/exterior.glb (nodes
# 'exterior' and 'sky'). At runtime:
#   * the sky (gradient dome with a warm city glow on the horizon, twinkling stars, the moon and its halo) gets its
#     shaders here (the JS ShaderMaterials) and follows the camera (level.cull() moves it);
#   * the tower beacons switch between their dark and lit materials: beacons.set_(on).
#
# buildExterior(game, extRoot, skyRoot) -> { sky: Node3D, beacons: { mesh, set_: Callable(on) } }
#   (Renames, SPEC §3.2: beacons.set -> beacons.set_ — a Dictionary holding a Callable, call it as
#   level.beacons.set_.call(on); the yard room may replace level.beacons with its own { mesh, set_ }.)
extends RefCounted

const Surf = preload("res://scripts/world/surfaces.gd")
const SKY_R := 150.0

# Sky dome: SKY_VERT/SKY_FRAG of exterior.js. Drawn at the far plane (three: gl_Position.z = w; Godot's reversed-Z
# far plane is z = 0), never writes depth, no fog. Colours are sRGB hex uniforms (source_color = linear like
# THREE.Color); the output is linear like three's before its colorspace_fragment.
const SKY_SHADER := """
shader_type spatial;
render_mode unshaded, cull_front, depth_draw_never, fog_disabled, shadows_disabled;
uniform vec3 uTop : source_color;
uniform vec3 uHorizon : source_color;
uniform vec3 uGlow : source_color;
uniform vec3 uGround : source_color;
varying vec3 vDir;
void vertex() {
	vDir = normalize(VERTEX);
	POSITION = PROJECTION_MATRIX * MODELVIEW_MATRIX * vec4(VERTEX, 1.0);
	POSITION.z = POSITION.w * 0.000001;
}
void fragment() {
	float h = vDir.y;
	vec3 c = mix(uHorizon, uTop, smoothstep(0.0, 0.6, h));
	c += uGlow * exp(-max(h, 0.0) * 11.0) * 0.85;
	c = mix(uGround, c, smoothstep(-0.04, 0.01, h));
	ALBEDO = c;
}
"""

# Stars: STAR_VERT/STAR_FRAG of exterior.js. three draws them as GL points (gl_PointSize px); the Blender mesh gives
# each star a quad whose 4 vertices sit on the star (UV = corner 0..1, UV2 = (aSize, aPhase)) and this shader
# expands it to the same pixel size on screen. uTime = realNow (TIME), additive, no depth write, no fog.
const STAR_SHADER := """
shader_type spatial;
render_mode unshaded, blend_add, depth_draw_never, cull_disabled, fog_disabled, shadows_disabled;
varying float vTw;
void vertex() {
	float aSize = UV2.x;
	float aPhase = UV2.y;
	vec4 p = PROJECTION_MATRIX * MODELVIEW_MATRIX * vec4(VERTEX, 1.0);
	vTw = 0.6 + 0.4 * sin(TIME * (1.3 + aPhase) + aPhase * 40.0);
	float size = aSize * (0.8 + 0.3 * vTw);
	p.xy += (UV * 2.0 - 1.0) * size / VIEWPORT_SIZE * p.w;
	p.z = p.w * 0.000002;
	POSITION = p;
}
void fragment() {
	float d = length(UV - 0.5);
	float a = smoothstep(0.5, 0.1, d);
	ALBEDO = vec3(1.0, 0.95, 0.82) * (0.5 + vTw);
	ALPHA = a;
}
"""

# Moon + halo: MeshBasicMaterial({ map: moonTexture(), color: PAL.moon x 1.35, transparent, depthWrite: false,
# fog: false }).
const MOON_SHADER := """
shader_type spatial;
render_mode unshaded, depth_draw_never, fog_disabled, shadows_disabled;
uniform vec3 uColor : source_color;
uniform float uMul = 1.35;
uniform sampler2D uMap : source_color, filter_linear_mipmap;
void fragment() {
	vec4 t = texture(uMap, UV);
	ALBEDO = uColor * uMul * t.rgb;
	ALPHA = t.a;
}
"""

static func buildExterior(game, extRoot: Node3D, skyRoot: Node3D) -> Dictionary:
	var sky := skyRoot if skyRoot != null else DAU.node3d("sky")
	sky.name = "sky"
	_skyMaterials(sky)
	return {"sky": sky, "beacons": _beacons(game, extRoot)}

static func _shader(code: String) -> Shader:
	var s := Shader.new()
	s.code = code
	return s

static func _skyMaterials(sky: Node3D) -> void:
	var dome := sky.find_child("sky_dome", true, false) as MeshInstance3D
	if dome != null:
		var m := ShaderMaterial.new()
		m.shader = _shader(SKY_SHADER)
		m.set_shader_parameter("uTop", Color(Config.PAL.skyTop))
		m.set_shader_parameter("uHorizon", Color(Config.PAL.horizon))
		m.set_shader_parameter("uGlow", Color("#6B3F6E"))
		m.set_shader_parameter("uGround", Color("#120E1E"))
		m.render_priority = -10
		dome.material_override = m
		dome.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		dome.extra_cull_margin = 16384.0       # frustumCulled = false
	var stars := sky.find_child("sky_stars", true, false) as MeshInstance3D
	if stars != null:
		var m2 := ShaderMaterial.new()
		m2.shader = _shader(STAR_SHADER)
		m2.render_priority = -9
		stars.material_override = m2
		stars.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF
		stars.extra_cull_margin = 16384.0
	var moon := sky.find_child("sky_moon", true, false) as MeshInstance3D
	if moon != null:
		var m3 := ShaderMaterial.new()
		m3.shader = _shader(MOON_SHADER)
		m3.set_shader_parameter("uColor", Color(Config.PAL.moon))
		var base := Surf.importedMat(moon)
		if base is BaseMaterial3D:
			m3.set_shader_parameter("uMap", (base as BaseMaterial3D).albedo_texture)
		m3.render_priority = -8
		moon.material_override = m3
		moon.cast_shadow = GeometryInstance3D.SHADOW_CASTING_SETTING_OFF

# Tower placeholder beacons: one merged mesh (tower_beacons), dark toon <-> lit glow ("da".mats {dark, lit}).
static func _beacons(game, extRoot: Node3D) -> Dictionary:
	var mesh := extRoot.find_child("tower_beacons", true, false) as MeshInstance3D if extRoot != null else null
	var st := {"dark": null, "lit": null}
	if mesh != null:
		DAU.ud(mesh).noMerge = true
		var da = Surf.nodeDa(mesh)
		var base := Surf.importedMat(mesh)
		if da != null and da.get("mats") is Dictionary:
			st.dark = Surf.matFromSpec(game, da.mats.get("dark"), base)
			st.lit = Surf.matFromSpec(game, da.mats.get("lit"), base)
		else:
			st.dark = Surf.meshMat(mesh)
			st.lit = st.dark
	return {"mesh": mesh, "set_": func(on):
		if mesh != null and is_instance_valid(mesh):
			mesh.material_override = st.lit if on else st.dark
	}
