# WZTV Channel 13 as plain data (port of src/world/layout.js; GDD §5, §13 toys, §18.2-18.6, §18.10, §18.13;
# ARCHITECTURE §7). The data itself is generated by blender/world/layout.py (the single source of truth of the
# station layout, a line-by-line port of layout.js incl. the derived WALLS / RAMPS) into res://data/layout.json;
# this script loads it once (static init) and fills the T-derived fields from Config.T, exactly like layout.js
# computed them at module load.
#
# Exports (static, same names and shapes as layout.js; arrays/objects are Arrays/Dictionaries, numbers are floats
# except the counting fields listed in INT_KEYS, which are ints):
#   FOOTPRINT                         {x0,z0,x1,z1} of the 0.5 m nav grid (GDD §5: x -7...51, z -30...6)
#   AREAS    [{ id, name, rect:[x0,z0,x1,z1], floorY, ceilY|null, floor, ambient, ambientPre, fog, adjacent,
#               doors, sky, accent }]           floor = footstep surface: carpet|tile|wood|gravel|metal
#   WALLS    [[x0,z0,x1,z1, y0,y1, kind, meta]]  thin boxes (WALL_T thick) centred on the segment;
#               kind 'solid'|'glass'|'fence'; meta = { sides:[negArea,posArea], jambs:[bool,bool], opening }
#   DOORS    [{ id, label, cost, areas, rect, y0, y1, width, height, line:[axis,at], span, center, look,
#               requiresPower, keypad, onAir }]  line ['x',7] = the wall x = 7; span = extent along it
#   WINDOWS  [{ id, label, area, type:'boarded'|'fence'|'gate', style, boards, inside, outside, spawn, spawns,
#               rotY, width, sill, top, line, span, wall:[x,z], entryTime }]
#   SCREEN_SPAWNS [{ id, area, pos, rotY, prop }]
#   PLATFORMS [{ id, area, rect, top, ramp, surface, kind }]  ramp > 0 = every edge ramps down over `ramp` m
#   BLOCKERS  [{ id, area, rect, y0, y1, tag }]   static architecture obstacles that are not walls (bleacher rails)
#   RAMPS     [{ id, rect, y0, y1, axis, dir, stairs? }]  ramp faces / stair steps derived from PLATFORMS
#   FLOOR_PATCHES [{ rect, surface }]            footstep surface overrides on the floor (MC metal plates)
#   ANCHORS   { id: { pos:[x,y,z], rotY, area, ...extra } }   (see layout.js for the list)
#   APPLAUSE_ZONE { rect }                       EE step 3 kill zone (T.ee.applauseZone)
#   areaAt(x, z) -> area id | null               pure lookup (rects are half-open)
#   WALL_T, ROOF_T, PARAPET, FENCE_H             building constants
#   AREA { id: area }                            (layout.js's private lookup, exposed for the world scripts)
# Usage: Layout.AREAS, Layout.areaAt(x, z) (class_name), or preload("res://scripts/world/layout.gd").
# The data is shared: treat it as read-only (duplicate(true) before mutating), like the JS module exports.
class_name Layout

const PATH := "res://data/layout.json"
# Fields that are counts in the JS (used with range() / as indices): converted from JSON floats to ints.
const INT_KEYS := ["boards", "count", "slots", "wedges", "detents", "phones", "grid"]

static var WALL_T := 0.3
static var ROOF_T := 0.3
static var PARAPET := 0.6
static var FENCE_H := 3.0
static var FOOTPRINT: Dictionary = {}
static var AREAS: Array = []
static var WALLS: Array = []
static var DOORS: Array = []
static var WINDOWS: Array = []
static var SCREEN_SPAWNS: Array = []
static var PLATFORMS: Array = []
static var BLOCKERS: Array = []
static var RAMPS: Array = []
static var FLOOR_PATCHES: Array = []
static var ANCHORS: Dictionary = {}
static var APPLAUSE_ZONE: Dictionary = {}
static var AREA: Dictionary = {}
static var loaded := false

static func _static_init() -> void:
	load_data()

static func load_data() -> void:
	if loaded:
		return
	var txt := FileAccess.get_file_as_string(PATH)
	var d = JSON.parse_string(txt) if txt != "" else null
	if not (d is Dictionary):
		push_error("[layout] cannot read %s (run blender/world/layout.py)" % PATH)
		return
	loaded = true
	WALL_T = float(d.WALL_T)
	ROOF_T = float(d.ROOF_T)
	PARAPET = float(d.PARAPET)
	FENCE_H = float(d.FENCE_H)
	FOOTPRINT = d.FOOTPRINT
	AREAS = d.AREAS
	WALLS = d.WALLS
	DOORS = d.DOORS
	WINDOWS = d.WINDOWS
	SCREEN_SPAWNS = d.SCREEN_SPAWNS
	PLATFORMS = d.PLATFORMS
	BLOCKERS = d.BLOCKERS
	RAMPS = d.RAMPS
	FLOOR_PATCHES = d.FLOOR_PATCHES
	ANCHORS = d.ANCHORS
	APPLAUSE_ZONE = d.APPLAUSE_ZONE
	_ints(WINDOWS)
	_ints(ANCHORS)
	for a in AREAS:
		AREA[a.id] = a
	# T-derived fields (layout.js reads them from config.js at module load).
	var T: Dictionary = Config.T
	for door in DOORS:
		door.cost = T.doors.get(door.id, 0)
	for w in WINDOWS:
		w.entryTime = T.zombies.fence if w.type == "fence" else (T.zombies.gate if w.type == "gate" else T.zombies.vault)
	APPLAUSE_ZONE.rect = T.ee.applauseZone
	ANCHORS.ee_applause_zone.rect = T.ee.applauseZone

static func _ints(v) -> void:
	if v is Dictionary:
		for k in v:
			if INT_KEYS.has(k):
				if v[k] is float:
					v[k] = int(v[k])
				elif v[k] is Array:
					for i in v[k].size():
						if v[k][i] is float:
							v[k][i] = int(v[k][i])
			else:
				_ints(v[k])
	elif v is Array:
		for x in v:
			_ints(x)

static func areaAt(x: float, z: float):
	for a in AREAS:
		var r: Array = a.rect
		if x >= r[0] and x < r[2] and z >= r[1] and z < r[3]:
			return a.id
	return null
